<form action="https://www.paypal.com/donate" method="post" target="_top">
<input type="hidden" name="business" value="UADQLQFJDND5J" />
<input type="hidden" name="no_recurring" value="0" />
<input type="hidden" name="item_name" value="Please help me fund my projects by donating via PayPal." />
<input type="hidden" name="currency_code" value="USD" />
<input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_donate_SM.gif" border="0" name="submit" title="Thank you for funding my projects with PayPal!" alt="Donate with PayPal button" />
<img alt="" border="0" src="https://www.paypal.com/en_BE/i/scr/pixel.gif" width="1" height="1" />
</form>
